<a href="https://colab.research.google.com/github/fanta0317/AI-summer-course/blob/main/20230704%E6%B7%A1%E6%B1%9F%E5%A4%A7%E5%AD%B8(week1day2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A=np.array([1,3,4])
print(type(A))
print(A.dtype)
print(A.ndim)
print(A.size)
print(A.shape)
print(A.reshape((-1,1)).shape)
print(A.reshape((-1,1)))
print(A.reshape((-1,3)))
print(A.shape)

<class 'numpy.ndarray'>
int64
1
3
(3,)
(3, 1)
[[1]
 [3]
 [4]]
[[1 3 4]]
(3,)


In [ ]:
print(A.reshape((-99,3)))
print(A.shape)

[[1 3 4]]
(3,)


In [ ]:
print(A.reshape((1,-1)))

[[1 3 4]]


In [ ]:
CA=A.reshape((-1,1))
print(A.shape)
print(CA.shape)
print(A)
print(CA)
print(CA.T)


(3,)
(3, 1)
[1 3 4]
[[1]
 [3]
 [4]]
[[1 3 4]]


In [ ]:
print(np.random.randint(0,10,(3,4)))

[[9 0 4 9]
 [4 8 0 3]
 [1 4 0 8]]


In [ ]:
R=(np.random.randint(1,10,(3,4)))
print(R)
print(np.min(R))
print(np.argmin(R))

[[1 2 8 7]
 [4 6 3 9]
 [9 7 1 1]]
1
0


In [ ]:
R=(np.random.randint(0,10,(3,4)))
print(R)
print("max =",np.max(R))
print("max in ",np.argmax(R))
print(np.sort(R,axis=0))#直的排序
print(np.sort(R,axis=1))#橫的排序
print(np.sort(R))#預設-->橫的排序

[[0 6 2 8]
 [4 0 8 5]
 [6 0 4 0]]
max = 8
max in  3
[[0 0 2 0]
 [4 0 4 5]
 [6 6 8 8]]
[[0 2 6 8]
 [0 4 5 8]
 [0 0 4 6]]
[[0 2 6 8]
 [0 4 5 8]
 [0 0 4 6]]


In [ ]:
print(np.arange(1,13))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
from numpy.core.fromnumeric import shape
AA=(np.arange(1,13))
print(AA)#生成1~12
print(AA.reshape((3,4)))#將AA塞入3*4矩陣

print(AA)#AA本質不變
AA.resize((3,4))#等於AA=AA.reshape((3,4))
print(AA)
print(AA.flatten())#攤開
AA=AA.flatten()
print(AA.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
AB=(np.random.randint(1,12,(3,4)))
print(AB)

[[ 6  5  6  7]
 [ 5 10  9 10]
 [ 5  4 10  5]]


In [ ]:
import numpy as np
def arrag_info(arr):
  print("size =",arr.size)
  print("shape =",arr.shape)
  print("dim =",arr.ndim)
  print("flatten =",arr.flatten())
#AC=0
AC=np.array(input())
arrag_info(AC)

[[0 6 2 8]  [4 0 8 5]  [6 0 4 0]]
size = 1
shape = ()
dim = 0
flatten = ['[[0 6 2 8]  [4 0 8 5]  [6 0 4 0]]']


In [ ]:
import numpy as np
def array_info(arr):
  size = arr.size
  shape = arr.shape
  dim = arr.ndim
  fla =arr.flatten()
  return size,shape,dim,fla
arr=(np.random.randint(1,12,(3,4)))
#print(arr)
#AC=0
#AC=np.array(input())
#arrag_info(AC)
for i in range (4):
  print(array_info(arr)[i])

12
(3, 4)
2
[ 5  7 10  1  8  6  2  1  1  9  6  3]


In [ ]:
print(AB)
BA=AB[:,1]
print(BA)
print(BA.shape)
print(AB[0][0])#預設為row
y=-1
x=-1
for i in range(3):

  y=y+1
  for j in range(4):

    x=x+1
    print(AB[x][y])


[[ 6  5  6  7]
 [ 5 10  9 10]
 [ 5  4 10  5]]
[ 5 10  4]
(3,)
6
6
5
5
5
10
4
6
9
10
7
10
5


In [ ]:
print(AB)
BA=AB[:,1]
print(BA)
print(BA.shape)
print(AB[0][0])#預設為row
print(AB[0:2,1:3])

[[ 6  5  6  7]
 [ 5 10  9 10]
 [ 5  4 10  5]]
[ 5 10  4]
(3,)
6
[[ 5  6]
 [10  9]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
data = pd.read_csv("clean.csv")
print(data)
data=data.to_numpy()
print(type(data))

     A1  A2  A3  S1  S2  S3  D1  D2     D3
0     2   4   4   4   4   4   4   4    NaN
1     1   5   4   5   5   5   5   5    NaN
2     2   3   3   3   5   5   4   4    NaN
3     2   5   4   4   4   4   4   1  999.0
4     2   3   3   4   5   5   4   5  999.0
..   ..  ..  ..  ..  ..  ..  ..  ..    ...
345   1   4   4   5   4   4   4   4    4.0
346   1   4   4   5   5   5   4   3    3.0
347   3   2   2   3   3   2   5   4    2.0
348   3   4   4   3   3   3   4   5    5.0
349   2   3   3   3   2   2   3   3    3.0

[350 rows x 9 columns]
<class 'numpy.ndarray'>
